//! DisplayBridge FFI surface — a hand-written C ABI over the pure `displaybridge-protocol`,
//! `displaybridge-session`, and `displaybridge-transport` crates.
//!
//! This crate is the transport-agnostic **session driver** that native platform
//! shells (Swift / Kotlin / C++ / C#) link against to run a DisplayBridge session.
//! It is the impure orchestrator that owns the wall clock and wires together:
//!
//! * a [`displaybridge_session::SessionMachine`] — the pure `event → command` handshake / ping /
//!   heartbeat logic (ported from the Swift `SessionCoordinator`),
//! * a transport — either the built-in Rust [`displaybridge_transport::TcpTransport`] (via
//!   [`displaybridge_session_connect_tcp`](ffi::displaybridge_session_connect_tcp)) or a native-owned one
//!   fed through [`displaybridge_session_feed_bytes`](ffi::displaybridge_session_feed_bytes) + the `send`
//!   callback (the Android USB path), and
//! * the native pipeline callbacks (`reconfigure` / `start_capture` / `stop_capture`
//!   for a source, `decode` for a sink) supplied in a [`types::DisplayBridgeCallbacks`] vtable.
//!
//! ## Roles
//! * **Source** (server): receives a `HandshakeReq`, replies `HandshakeAck`, starts
//!   capture, then streams frames submitted via
//!   [`displaybridge_session_submit_frame`](ffi::displaybridge_session_submit_frame). The `SessionMachine`
//!   drives this end to end, including the ping heartbeat while streaming.
//! * **Sink** (client): on connect it sends a `HandshakeReq` carrying its
//!   [`displaybridge_session_set_config`](ffi::displaybridge_session_set_config) display config, and on each
//!   incoming `VideoFrame` it unwraps the NAL and calls the native `decode` callback.
//!   Ping is answered with Pong by the shared machine.
//!
//! ## Safety model
//! Handles are opaque; every entry point null-checks its pointers and is wrapped in
//! `catch_unwind`, so a Rust panic never unwinds across the C boundary. All background
//! threads are stopped and joined in [`displaybridge_session_destroy`](ffi::displaybridge_session_destroy),
//! which is the only way to free a handle.
//!
//! ## Header
//! The C header (`include/displaybridge_ffi.h`) is regenerated by `build.rs` (via cbindgen) on
//! every `cargo build` from the `#[repr(C)]` / `extern "C"` items here.
//!
//! ## Future work
//! UniFFI is intentionally out of scope: a hand-written C ABI is the lowest common
//! denominator all six target platforms consume. Ergonomic UniFFI Kotlin/Swift
//! wrappers can layer on top of this ABI in the later platform phases.

mod driver;
pub mod ffi;
pub mod types;

pub use ffi::{
    displaybridge_session_connect_tcp, displaybridge_session_create, displaybridge_session_destroy, displaybridge_session_feed_bytes,
    displaybridge_monotonic_ns, displaybridge_session_notify_connected, displaybridge_session_send_input, displaybridge_session_set_config, displaybridge_session_set_pairing_code, displaybridge_session_submit_frame, displaybridge_session_wants_frame, DisplayBridgeSession,
};
pub use types::{DisplayBridgeCallbacks, DisplayBridgeClientStats, DisplayBridgeDeviceConfig, DisplayBridgeInputEvent, DisplayBridgeRole, DisplayBridgeSessionState, DisplayBridgeVideoCodec};
