#ifndef DISPLAYBRIDGE_FFI_H
#define DISPLAYBRIDGE_FFI_H

#pragma once

/* AUTO-GENERATED by cbindgen from the displaybridge-ffi crate. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * The role this session plays, mirroring `displaybridge_protocol::Role`.
 */
enum DisplayBridgeRole
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  /**
   * Owns and captures a display; encodes and sends frames. (server)
   */
  DisplayBridgeRole_Source = 0,
  /**
   * Receives frames, decodes and renders them. (client)
   */
  DisplayBridgeRole_Sink = 1,
};
#ifndef __cplusplus
typedef uint32_t DisplayBridgeRole;
#endif // __cplusplus

/**
 * Observable session lifecycle state, mirroring `displaybridge_session::SessionState`.
 */
enum DisplayBridgeSessionState
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  /**
   * No session yet.
   */
  DisplayBridgeSessionState_Idle = 0,
  /**
   * The transport is being established.
   */
  DisplayBridgeSessionState_Connecting = 1,
  /**
   * Connected; negotiating the handshake.
   */
  DisplayBridgeSessionState_Negotiating = 2,
  /**
   * Handshake complete; frames are flowing.
   */
  DisplayBridgeSessionState_Streaming = 3,
  /**
   * The session has ended.
   */
  DisplayBridgeSessionState_Disconnected = 4,
};
#ifndef __cplusplus
typedef uint32_t DisplayBridgeSessionState;
#endif // __cplusplus

/**
 * The video codec, mirroring `displaybridge_protocol::VideoCodec`.
 */
enum DisplayBridgeVideoCodec
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  /**
   * H.265 / HEVC.
   */
  DisplayBridgeVideoCodec_Hevc = 0,
  /**
   * H.264 / AVC.
   */
  DisplayBridgeVideoCodec_H264 = 1,
  /**
   * AV1 (reserved; not negotiated yet).
   */
  DisplayBridgeVideoCodec_Av1 = 2,
};
#ifndef __cplusplus
typedef uint32_t DisplayBridgeVideoCodec;
#endif // __cplusplus

/**
 * Opaque session handle returned by [`displaybridge_session_create`]. Native code only ever
 * holds a `*mut DisplayBridgeSession` and passes it back to the other entry points.
 */
typedef struct DisplayBridgeSession DisplayBridgeSession;

/**
 * A display configuration passed across the boundary.
 *
 * `device_name` is a NUL-terminated UTF-8 C string and may be null.
 */
typedef struct {
  /**
   * Display width in pixels.
   */
  int32_t width;
  /**
   * Display height in pixels.
   */
  int32_t height;
  /**
   * Refresh rate in Hz.
   */
  int32_t refresh_rate;
  /**
   * The negotiated / requested codec.
   */
  DisplayBridgeVideoCodec codec;
  /**
   * Optional human-readable device name (nullable, NUL-terminated UTF-8).
   */
  const char *device_name;
} DisplayBridgeDeviceConfig;

/**
 * Lightweight per-interval pipeline stats, mirroring `displaybridge_session::ClientStats`.
 */
typedef struct {
  /**
   * Frames captured per second.
   */
  double capture_fps;
  /**
   * Frames sent per second.
   */
  double sent_fps;
  /**
   * Percentage of captured frames dropped.
   */
  double dropped_percent;
  /**
   * Average send latency in milliseconds.
   */
  double avg_latency_ms;
  /**
   * Peak send latency in milliseconds.
   */
  double max_latency_ms;
} DisplayBridgeClientStats;

/**
 * A pointer event, mirroring `displaybridge_protocol::InputEvent`.
 *
 * `kind` is a raw byte rather than an enum so an out-of-range value coming from
 * native code is rejected instead of being undefined behaviour:
 * 0 down, 1 move, 2 up, 3 scroll, 4 hover.
 */
typedef struct {
  /**
   * 0 down, 1 move, 2 up, 3 scroll, 4 hover.
   */
  uint8_t kind;
  /**
   * 0 primary, 1 secondary.
   */
  uint8_t button;
  /**
   * Position, 0..1 across the display width.
   */
  float x;
  /**
   * Position, 0..1 down the display height.
   */
  float y;
  /**
   * Scroll delta as a fraction of the display width.
   */
  float dx;
  /**
   * Scroll delta as a fraction of the display height.
   */
  float dy;
  /**
   * Pressure, 0..1 (1.0 for a plain touch or click).
   */
  float pressure;
} DisplayBridgeInputEvent;

/**
 * Native callback vtable, supplied at session creation.
 *
 * `ctx` is an opaque pointer handed back to every callback; the native side owns
 * its lifetime and thread-safety. Any function pointer may be null — the driver
 * null-checks before calling. The driver invokes these from its internal reader
 * and clock threads, so the native `ctx` and callbacks must be thread-safe.
 */
typedef struct {
  /**
   * Opaque context pointer passed to every callback.
   */
  void *ctx;
  /**
   * Write already-framed bytes to a native-owned transport (Android USB path).
   * Null when the built-in Rust transport (`displaybridge_session_connect_tcp`) is used.
   */
  void (*send)(void *ctx, const uint8_t *data, uintptr_t len);
  /**
   * Source hook: (re)build the capture/encode pipeline for `config`.
   */
  void (*reconfigure)(void *ctx, const DisplayBridgeDeviceConfig *config);
  /**
   * Source hook: start capturing/encoding for `config`.
   */
  void (*start_capture)(void *ctx, const DisplayBridgeDeviceConfig *config);
  /**
   * Source hook: stop the current capture.
   */
  void (*stop_capture)(void *ctx);
  /**
   * Sink hook: deliver a decoded-ready NAL unit to the native decoder.
   */
  void (*decode)(void *ctx,
                 const uint8_t *nal,
                 uintptr_t len,
                 bool is_keyframe,
                 uint64_t timestamp_micros);
  /**
   * Optional: observe session state transitions.
   */
  void (*on_state_change)(void *ctx, DisplayBridgeSessionState state);
  /**
   * Optional: receive periodic pipeline stats (source only).
   */
  void (*on_stats)(void *ctx, DisplayBridgeClientStats stats);
  /**
   * Source hook: a pointer event arrived from the sink; inject it into the display.
   */
  void (*on_input)(void *ctx, DisplayBridgeInputEvent event);
  /**
   * Optional: the peer refused the session (e.g. a wrong pairing code). `message`
   * is NUL-terminated UTF-8 meant for the user, valid only during the call.
   */
  void (*on_error)(void *ctx, const char *message);
} DisplayBridgeCallbacks;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a session driver for `role`, wiring in the native callback vtable.
 *
 * Spawns the background clock thread. Returns an opaque handle, or null on failure.
 * The handle must be released with [`displaybridge_session_destroy`]; nothing else frees it.
 */
DisplayBridgeSession *displaybridge_session_create(DisplayBridgeRole role,
                                                   DisplayBridgeCallbacks callbacks);

/**
 * Sets the display config a sink advertises in its `HandshakeReq`.
 *
 * Call on a sink session before [`displaybridge_session_connect_tcp`]. Ignored for a source
 * (which learns the config from the incoming handshake). Returns `false` if either
 * pointer is null.
 *
 * # Safety
 * `handle` must be a live handle from [`displaybridge_session_create`]; `config` (and its
 * `device_name`, if set) must be valid for the duration of the call.
 */
bool displaybridge_session_set_config(DisplayBridgeSession *handle,
                                      const DisplayBridgeDeviceConfig *config);

/**
 * Sets the pairing code. On a source, every sink must then present this code in its
 * handshake or be refused; on a sink, it is the code presented. Call before
 * connecting. Returns `false` on a null handle, or a null / empty / non-UTF-8 code.
 *
 * # Safety
 * `handle` must be a live handle; `code` must be a valid NUL-terminated string.
 */
bool displaybridge_session_set_pairing_code(DisplayBridgeSession *handle, const char *code);

/**
 * Convenience for network shells: builds a Rust-owned TCP transport, wires it to the
 * driver, dials `host:port`, and feeds a `Connected` event.
 *
 * A sink additionally sends its `HandshakeReq` here (set its config first). Returns
 * `false` on a null handle/host or any connection failure.
 *
 * # Safety
 * `handle` must be a live handle; `host` must be a valid NUL-terminated UTF-8 string.
 */
bool displaybridge_session_connect_tcp(DisplayBridgeSession *handle,
                                       const char *host,
                                       uint16_t port);

/**
 * Reads the core's process-global monotonic clock, in nanoseconds.
 *
 * Native code should stamp a frame's capture time with this (and pass it to
 * [`displaybridge_session_submit_frame`] as `capture_time_ns`) so the driver's
 * send-latency measurement shares one epoch with the capture timestamp. Mixing a
 * platform clock (e.g. Apple `DispatchTime` uptime) with the core's clock makes
 * `now - capture` underflow and report zero latency. Safe to call anytime.
 */
uint64_t displaybridge_monotonic_ns(void);

/**
 * Signals that a native-owned transport has connected.
 *
 * The native-owned-transport counterpart of the `Connected` event that
 * [`displaybridge_session_connect_tcp`] feeds automatically: it drives the machine to
 * `Negotiating` and, for a sink, sends the opening `HandshakeReq` (set its config
 * first). Call exactly once, after the native transport is ready and before feeding
 * bytes. Do NOT call it when using the built-in Rust transport. No-op on a null handle.
 *
 * # Safety
 * `handle` must be a live handle from [`displaybridge_session_create`].
 */
void displaybridge_session_notify_connected(DisplayBridgeSession *handle);

/**
 * Feeds bytes received on a native-owned transport (Android USB) into the driver.
 *
 * The driver buffers, reframes with the shared packet framer, and processes each
 * complete packet. No-op on a null handle or null/empty buffer.
 *
 * # Safety
 * `handle` must be a live handle; `data` must point to `len` readable bytes.
 */
void displaybridge_session_feed_bytes(DisplayBridgeSession *handle,
                                      const uint8_t *data,
                                      uintptr_t len);

/**
 * Source data plane: asks whether the frame just captured should be encoded at all.
 *
 * Call this before encoding each captured frame and skip the frame on `false` (not
 * streaming, or the previous frame has not reached the wire yet). Skipping before the
 * encoder keeps its reference chain intact; dropping an already encoded frame would
 * corrupt the picture until the next keyframe. Returns `false` on a null handle.
 *
 * # Safety
 * `handle` must be a live handle from [`displaybridge_session_create`].
 */
bool displaybridge_session_wants_frame(DisplayBridgeSession *handle);

/**
 * Source data plane: hands an already hardware-encoded frame to the driver.
 *
 * The driver frames it as a `VideoFrame` and queues it for its sender thread, which
 * writes it to the active transport and records metrics; this call does not block on
 * the write. No-op on a null
 * handle or null/empty buffer, or if the session is not streaming.
 *
 * # Safety
 * `handle` must be a live handle; `encoded` must point to `len` readable bytes.
 */
void displaybridge_session_submit_frame(DisplayBridgeSession *handle,
                                        const uint8_t *encoded,
                                        uintptr_t len,
                                        bool is_keyframe,
                                        uint64_t capture_time_ns);

/**
 * Sink input plane: forwards a pointer event to the source, which injects it into
 * the display it is sharing.
 *
 * Returns `false` on a null handle, an unknown `event.kind`, a session that is not a
 * streaming sink, or a failed write.
 *
 * # Safety
 * `handle` must be a live handle from [`displaybridge_session_create`].
 */
bool displaybridge_session_send_input(DisplayBridgeSession *handle, DisplayBridgeInputEvent event);

/**
 * Stops the driver's threads, disconnects the transport, and frees the handle.
 *
 * After this returns the handle is invalid and must not be used again. No-op on null.
 *
 * # Safety
 * `handle` must be a live handle from [`displaybridge_session_create`] that has not already been
 * destroyed.
 */
void displaybridge_session_destroy(DisplayBridgeSession *handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DISPLAYBRIDGE_FFI_H */
